---
# depends: Ubuntu + desktop GUI
#
# Matlab installation requires you to have prepared 2 files:
#  1) target machine must locally have a file with Matlab software ISO image 
#    NB: You should obtain this ISO image from MathWorks Inc.
#
#  2) target machine must locally have a file with configuration information
#    NB: file format should be yaml, suggested variables are:
#     matlab_file_installation_key
#     matlab_license_text
#     matlab_products  (specify here if not all products are to be installed)
#
# As an alternative approach to 2) one could provide the variables as part of an Ansible playbook
#
- name: Check if the configuration file exists
  ansible.builtin.stat:
    path: "{{ matlab_configfile_path }}"
  register: matlab_c

- name: If config file exists, load its content into Ansible vars
  ansible.builtin.include_vars:
    file: "{{ matlab_configfile_path }}"
  when: matlab_c.stat.exists

- name: Create mountpoint /mnt/matlab-iso
  ansible.builtin.file:
    dest: /mnt/matlab-iso
    state: directory
    mode: "0755"
    owner: root
    group: root

- name: Mount Matlab software iso image as /mnt/matlab-iso
  ansible.posix.mount:
    path: /mnt/matlab-iso
    src: "{{ matlab_iso_dir }}/{{ matlab_iso_file }}"
    fstype: iso9660
    opts: loop
    state: mounted

- name: Prepare a silent install inputfile
  ansible.builtin.template:
    owner: root
    group: root
    mode: "0644"
    src: installer_input.txt.j2
    dest: /root/matlab_installer_input.txt

- name: Prepare the license.dat file
  ansible.builtin.template:
    owner: root
    group: root
    mode: "0644"
    src: license.dat.j2
    dest: /root/license.dat

- name: Create Matlab target dir
  ansible.builtin.file:
    dest: "{{ matlab_dir }}"
    state: directory
    mode: "0755"
    owner: root
    group: root

# NB: may take 30 min and 20 GB disk space for full product install
- name: Install Matlab products using silent installation. check log in /tmp for progress
  ansible.builtin.command: /mnt/matlab-iso/install -inputFile /root/matlab_installer_input.txt
  args:
    chdir: /mnt/matlab-iso
  register: matlab_i

# TODO: even if unsuccessful, the matlab install script will report success :(
#- name: check install result
#  debug:
#    msg: "rc = {{matlab_i.rc}}"

- name: Ensure filesystems are at rest before unmount
  ansible.builtin.command: sync
- name: Unmount Matlab software iso image, no longer needed
  ansible.posix.mount:
    path: /mnt/matlab-iso
    state: unmounted

- name: Install desktop launcher
  ansible.builtin._include: desktop.yml
- name: Create commandline wrapper to matlab executable
  ansible.builtin.template:
    owner: root
    group: root
    mode: "0755"
    src: matlab.j2
    dest: /usr/local/bin/matlab
