---
- name: Add config to nginx to act as reverse proxy for keycloak
  ansible.builtin.copy:
    src: keycloak.conf
    dest: /etc/nginx/app-location-conf.d/keycloak.conf
    mode: "0644"

- name: Restart nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted
