---
- name: Check if the robotuser connection info file exist
  ansible.builtin.stat:
    path: /home/{{ robotuser_name }}/connection-info.yml
  register: robotuser_c

- name: If config file exists, load its content into Ansible vars
  ansible.builtin.include_vars:
    file: /home/{{ robotuser_name }}/connection-info.yml
  when: robotuser_c.stat.exists
