---
- name: Verify
  hosts: all
  gather_facts: true
  tasks:
    - name: Test ASReview
      ansible.builtin.uri:
        url: http://localhost/
        method: GET
        follow_redirects: safe
        return_content: true
      register: get_asreview

    - name: Assert reverse proxy working correctly
      ansible.builtin.assert:
        that:
          - get_asreview.redirected is false
          - "'ASReview' in get_asreview.content"