---
# End playbook if the default value was not overwrittien (argument needs a default value)
- name: End playbook if no repository supplied
  ansible.builtin.meta: end_play
  when: repositories == 'default'

- name: Create list of repos to checkout
  ansible.builtin.set_fact:
    repos: '"{{'
    cmd: repositories.split(';') }}"
- name: Clone each repo from list if URL does NOT end with '.git'
  when: "'.git' not in item"
  ansible.builtin.git:
    repo: "{{ item }}"
    dest: "{{ git_dir }}/{{ item | basename }}"
  with_items:
    - "{{ repos }}"
  environment:
    GIT_TERMINAL_PROMPT: 0 #Disables stdout prompt (e.g. password prompt)

- name: Clone each repo from list if URL DOES end with '.git'
  when: "'.git' in item"
  ansible.builtin.git:
    repo: "{{ item }}"
    dest: "{{ git_dir }}/{{ item[:-4] | basename }}"
  with_items:
    - "{{ repos }}"
  environment:
    GIT_TERMINAL_PROMPT: 0 #Disables stdout prompt (e.g. password prompt)
