---
- name: Download poetry installer
  ansible.builtin.get_url:
    url: https://install.python-poetry.org
    dest: /tmp/install-poetry.py
    mode: "0777"
    timeout: 20

- name: Install venv dependency
  ansible.builtin.apt:
    name: python3-venv

- name: Install poetry system-wide
  ansible.builtin.command: python3 /tmp/install-poetry.py
  environment:
    POETRY_HOME: /opt/poetry

- name: Clean installation file
  ansible.builtin.file:
    path: /tmp/install-poetry.py
    state: absent
