---
- name: Install PostgreSQL.
  ansible.builtin.apt:
    state: present
    pkg:
      - postgresql
      - postgresql-server

- name: Register if PostgreSQL is initialized.
  ansible.builtin.stat:
    path: /var/lib/pgsql/data/pg_hba.conf
  register: prostgresql_data

- name: Initilize PostgreSQL if not yet.
  when: not postgresql_data.exists
  ansible.builtin.command: postgresql-setup initdb
- name: Start PostgreSQL service
  ansible.builtin.service:
    name: postgresql
    state: restarted
    enabled: true

- name: Provision db and user by default
  when: postgresql_provision
  ansible.builtin._include: provision.yml
