---
- name: End play if not on Ubuntu
  meta: end_play
  when: ansible_distribution != "Ubuntu"

- name: Install package
  ansible.builtin.apt:
    name: unattended-upgrades
    update_cache: true
    state: present

- name: Install security updates
  block:
  - name: Run updates
    command: unattended-upgrades -v
    tags: molecule-notest

  - name: Run updates # dry run
    command: unattended-upgrades --dry-run
    changed_when: false
    when: "'molecule-notest' in ansible_skip_tags"
  when: security_updates_firstrun == true

- name: Enable periodic updates
  block:
    - name: Install bootstrap script
      copy:
        src: start_upgrade_timers.sh
        dest: /usr/local/bin/start_upgrade_timers.sh
        owner: root
        mode: 0740

    - name: Install bootstrapping service definition
      copy:
        src: upgrade-timer-bootstrap.service
        dest: /etc/systemd/system/upgrade-timer-bootstrap.service
        owner: root
        mode: 0740

    - name: Install bootstrapping timer definition
      template:
        src: upgrade-timer-bootstrap.timer
        dest: /etc/systemd/system/upgrade-timer-bootstrap.timer

    - name: Enable bootstrap timer
      command: "{{ item }}"
      with_items:
        - systemctl enable upgrade-timer-bootstrap.timer
        - systemctl start upgrade-timer-bootstrap.timer
  when: security_updates_periodic == true