---
- name: End play if not on Ubuntu
  meta: end_play
  when: ansible_distribution != "Ubuntu"

- name: Install package
  ansible.builtin.apt:
    name: unattended-upgrades
    update_cache: true
    state: present

- name: Install security updates
  block:
  - name: Run updates
    command: unattended-upgrades -v
    tags: molecule-notest

  - name: Run updates # dry run
    command: unattended-upgrades --dry-run
    changed_when: false
    when: "'molecule-notest' in ansible_skip_tags"
  when: security_updates_firstrun == true

- name: Enable unattended upgrades
  command: "{{ item }}"
  tags: molecule-notest # systemctl not active on test container
  with_items:
    - systemctl enable apt-daily.timer
    - systemctl enable apt-daily-upgrade.timer
    - systemctl start apt-daily.timer
    - systemctl start apt-daily-upgrade.timer
  when: security_updates_periodic == true