---
- name: Get ownCloud APT GPG key
  ansible.builtin.apt_key:
    url: https://download.owncloud.com/desktop/ownCloud/stable/latest/linux/Ubuntu_{{ ubuntu_version }}/Release.key
    state: present

- name: Configure ownCloud apt repository
  ansible.builtin.apt_repository:
    repo: deb https://download.owncloud.com/desktop/ownCloud/stable/latest/linux/Ubuntu_{{ ubuntu_version }}/ /
    state: present
    update_cache: true

- name: Clear APT cache then install ownCloud package
  ansible.builtin.apt:
    name: owncloud-client
    update_cache: "yes"
    cmd: ""
