---
- name: Overwrite conda installation dir
  ansible.builtin.set_fact:
    miniconda_install_dir: "{{ item.home }}/miniconda"

- name: Install conda for each user individually
  ansible.builtin.command: "{{ miniconda_download_dest }}/miniconda.sh -b -p {{ miniconda_install_dir }}"
  become: false
  become_user: "{{ item.user }}"
