driver:
  name: docker
  local: &local
    pull: false
  ci: &ci
    pull: true
    registry:
      url: $DOCKER_REGISTRY
      credentials:
        username: $DOCKER_USER
        password: $DOCKER_PW
platforms:
  - name: workspace-src-ubuntu_jammy
    image: ghcr.io/utrechtuniversity/src-test-workspace:ubuntu_jammy
    pre_build_image: true
    # Include &ci (ensures the image is pulled from the repository) if CI env variable is set
    # Otherwise include &loca (ensures the image is not pulled).
    <<: ${CI-*local}
  - name: workspace-src-ubuntu_focal
    image: ghcr.io/utrechtuniversity/src-test-workspace:ubuntu_focal
    pre_build_image: true
    # Include &ci (ensures the image is pulled from the repository) if CI env variable is set
    # Otherwise include &loca (ensures the image is not pulled).
    <<: ${CI-*local}
provisioner:
  name: ansible
  env:
    PLAYBOOK_PATH: 'security_updates.yml'
