---
name: Podman
on:
  push:
  pull_request:

jobs:
  podman:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to ghcr.io
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
      - name: Try manually pulling podman image
        run: |
          set +e
          getent passwd runner
          getent passwd root
          echo "USER: `whoami`"
          sudo ls -l /var/lib/containers
          cat <<EOF > Containerfile
          FROM registry.access.redhat.com/ubi8/ubi-init
          RUN yum -y install httpd; yum clean all; systemctl enable httpd;
          RUN echo "Successful Web Server Test" > /var/www/html/index.html
          RUN mkdir /etc/systemd/system/httpd.service.d/; echo -e '[Service]\nRestart=always' > /etc/systemd/system/httpd.service.d/httpd.conf
          EXPOSE 80
          CMD [ "/sbin/init" ]
          EOF
          podman build --format=docker -t podmantest .
          podman run -d -p 8080:80 podmantest /sbin/init
          podman ps --all
          podman pull ghcr.io/utrechtuniversity/src-test-workspace:ubuntu_focal
          podman run -d ghcr.io/utrechtuniversity/src-test-workspace:ubuntu_focal /sbin/init
          podman ps --all